# -*- coding: utf-8 -*-
"""Untitled421.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flzcUSfxp3sQrswptPIgbyhpgDOdEfNJ
"""

import keras

def char_to_index(char):
    """
    Convierte un carácter de 'a' a 'z' en un índice numérico (0-25) o un espacio en 26.
    Por ejemplo, 'a' retorna 0, 'b' retorna 1, ' ' retorna 26.

    Args:
        char (str): El carácter a convertir. Debe ser una letra minúscula de 'a' a 'z' o un espacio.

    Returns:
        int: El índice numérico del carácter.

    Raises:
        ValueError: Si el carácter no es una letra minúscula de 'a' a 'z' ni un espacio.
    """
    if char == ' ':
        return 26

    if not isinstance(char, str) or len(char) != 1 or not ('a' <= char <= 'z') :
        raise ValueError("El input debe ser un solo carácter minúsculo de 'a' a 'z' o un espacio.")
    return ord(char) - ord('a')

# Ejemplo de uso:
# print(f"'a' -> {char_to_index('a')}")
# print(f"'c' -> {char_to_index('c')}")
# print(f"'z' -> {char_to_index('z')}")
# print(f"' ' -> {char_to_index(' ')}")

# # Esto generaría un error:
# # char_to_index('A')
# # char_to_index('1')
# # char_to_index('ab')

def index_to_char(index):
    """
    Convierte un índice numérico (0-26) de nuevo a su carácter correspondiente ('a'-'z' o espacio).
    Por ejemplo, 0 retorna 'a', 1 retorna 'b', 26 retorna ' '.

    Args:
        index (int): El índice numérico a convertir. Debe estar en el rango [0, 26].

    Returns:
        str: El carácter correspondiente al índice.

    Raises:
        ValueError: Si el índice no está en el rango [0, 26].
    """
    if not isinstance(index, int) or not (0 <= index <= 26):
        raise ValueError("El índice debe ser un entero entre 0 y 26.")

    if index == 26:
        return ' '
    else:
        return chr(ord('a') + index)

# Ejemplo de uso:
# print(f"0 -> {index_to_char(0)}")
# print(f"25 -> {index_to_char(25)}")
# print(f"26 -> {index_to_char(26)}")

# # Esto generaría un error:
# # index_to_char(27)
# # index_to_char(-1)

import numpy as np

def index_to_onehot(index):
    """
    Convierte un índice numérico (0-26) en un vector one-hot de tamaño 27.
    El índice 26 representa el espacio.

    Args:
        index (int): El índice a convertir. Debe estar en el rango [0, 26].

    Returns:
        np.ndarray: Un vector one-hot de tamaño 27.

    Raises:
        ValueError: Si el índice no está en el rango [0, 26].
    """
    if not isinstance(index, int) or not (0 <= index <= 26):
        raise ValueError("El índice debe ser un entero entre 0 y 26.")

    onehot = np.zeros(27, dtype=int)
    onehot[index] = 1
    return onehot

# Ejemplo de uso:
# print(f"0 -> {index_to_onehot(0)}")
# print(f"5 -> {index_to_onehot(5)}")
# print(f"25 -> {index_to_onehot(25)}")
# print(f"26 (espacio) -> {index_to_onehot(26)}")

# # Esto generaría un error:
# # index_to_onehot(27)
# # index_to_onehot(-1)

def clean_text(text):
    """
    Recibe un texto y elimina todo lo que no sean caracteres de 'a' a 'z' (minúsculas) y espacios en blanco.

    Args:
        text (str): El texto a limpiar.

    Returns:
        str: El texto limpio con solo letras minúsculas y espacios.
    """
    cleaned_chars = []
    for char in text:
        if 'a' <= char.lower() <= 'z' or char == ' ':
            cleaned_chars.append(char.lower())
    return ''.join(cleaned_chars)

# Ejemplo de uso:
# text_example = "¡Hola, Mundo 123! Esto es una Prueba con Caracteres especiales: @#$%
# print(f"Texto original: {text_example}")
# print(f"Texto limpio: {clean_text(text_example)}")

def remove_duplicate_spaces_and_newlines(text):
    """
    Recibe un texto, elimina los saltos de línea y reemplaza los espacios duplicados por un solo espacio.

    Args:
        text (str): El texto a procesar.

    Returns:
        str: El texto limpio con espacios normalizados y sin saltos de línea.
    """
    # Reemplazar saltos de línea con espacios
    text_no_newlines = text.replace('\n', ' ').replace('\r', ' ')
    # Eliminar espacios duplicados
    cleaned_text = ' '.join(text_no_newlines.split())
    return cleaned_text

# Ejemplo de uso:
# example_text = """Este es  un texto
# con
#   espacios   duplicados
# y saltos de linea."""
# print(f"Texto original:\n{example_text}")
# print(f"Texto limpio:\n{remove_duplicate_spaces_and_newlines(example_text)}")


def create_sliding_windows(sequence, window_size):
    """
    Crea ventanas deslizantes de un tamaño específico de una secuencia para generar
    pares de entrada (X) y salida (y).

    Args:
        sequence (list or str): La secuencia de datos de la que se extraerán las ventanas.
        window_size (int): El tamaño de la ventana deslizante.

    Returns:
        tuple: Una tupla que contiene dos listas:
               - X (list): Una lista de secuencias de entrada.
               - y (list): Una lista de elementos de salida correspondientes.
    """
    X = []
    y = []
    for i in range(len(sequence) - window_size):
        X.append(sequence[i:i + window_size])
        y.append(sequence[i + window_size])
    return X, y

